version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: beleqet-postgres
    restart: always
    environment:
      POSTGRES_USER: beleqet_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: beleqet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: beleqet-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beleqet-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgresql://neondb_owner:npg_YdKUR0k3TmEa@ep-rapid-star-adbnh6rm-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_TLS=false
      - JWT_ACCESS_SECRET=MyMy#KEY12@!!$#%^RWEx12^(.Y.)MyMy#KEY12@!!$#%^RWEx12^
      - JWT_ACCESS_EXPIRES=15m
      - JWT_REFRESH_EXPIRES=30d
      - OPENAI_API_KEY=sk-...
      - OPENAI_MODEL=gpt-4o-mini
      - TELEGRAM_BOT_TOKEN=8987895308:AAG5w5o1WjyCPgCZcIEjCumGgMr9NMW9Eh0
      - TELEGRAM_CHANNEL_ID=-1001234567890
      - CHAPA_SECRET_KEY=CHASECK_TEST-...
      - CHAPA_PUBLIC_KEY=CHAPUBK_TEST-...
      - CHAPA_WEBHOOK_SECRET=your_webhook_secret
      - CHAPA_CALLBACK_URL=http://localhost:4000/api/v1/escrow/callback
      - CHAPA_RETURN_URL=http://localhost:3000/freelance/payment-success
      - AWS_S3_BUCKET=beleqet-uploads
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=us-east-1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=eshetugetsh19@gmail.com
      - SMTP_PASS=tnxh gbaw mqdu spzi
      - EMAIL_FROM=Beleqet <noreply@beleqet.com>
      - BULL_BOARD_USERNAME=admin
      - BULL_BOARD_PASSWORD=your_board_password 

    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
